//! PLR group operations — the D₁₂ algebra that guarantees valid voice leading.

/// A PLR group operation on triads.
///
/// The PLR group is generated by three involutions (each is its own inverse):
/// - **P** (Parallel): swaps major ↔ minor, keeps root fixed
/// - **L** (Leading-tone exchange): swaps major ↔ minor, shifts by semitone
/// - **R** (Relative): swaps major ↔ minor, shifts by relative interval
///
/// The group generated by {P, L, R} is isomorphic to D₁₂ (the dihedral group
/// of order 24), acting transitively on the set of 24 major and minor triads.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Operation {
    P,
    L,
    R,
}

/// Compose a sequence of PLR operations into a single effective operation.
///
/// Returns the net transformation as a sequence (because the PLR group has 24 elements,
/// not just P/L/R). For simplicity, returns the sequence of basic operations.
pub fn compose_operations(ops: &[Operation]) -> Vec<Operation> {
    ops.to_vec()
}

impl std::fmt::Display for Operation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Operation::P => write!(f, "P"),
            Operation::L => write!(f, "L"),
            Operation::R => write!(f, "R"),
        }
    }
}

impl Operation {
    /// Parse from string: "P", "L", "R" (case-insensitive).
    pub fn parse_op(s: &str) -> Option<Self> {
        match s.to_uppercase().as_str() {
            "P" => Some(Operation::P),
            "L" => Some(Operation::L),
            "R" => Some(Operation::R),
            _ => None,
        }
    }

    /// All three basic operations.
    pub fn all() -> &'static [Operation; 3] {
        &[Operation::P, Operation::L, Operation::R]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn display_operations() {
        assert_eq!(format!("{}", Operation::P), "P");
        assert_eq!(format!("{}", Operation::L), "L");
        assert_eq!(format!("{}", Operation::R), "R");
    }

    #[test]
    fn parse_operations() {
        assert_eq!(Operation::parse_op("P"), Some(Operation::P));
        assert_eq!(Operation::parse_op("l"), Some(Operation::L));
        assert_eq!(Operation::parse_op("R"), Some(Operation::R));
        assert_eq!(Operation::parse_op("X"), None);
    }

    #[test]
    fn all_operations() {
        assert_eq!(Operation::all().len(), 3);
    }
}
